### ISSUE TITLE
readme is broken

### ISSUE THREAD

**Issue by PatrickJS** [blakeembrey/highlighter#1]
<img width="900" alt="screen shot 2015-09-05 at 11 11 41 pm" src="https://cloud.githubusercontent.com/assets/1016365/9702857/85fc9f48-5423-11e5-96da-12428bae50de.png">

this is broken

**Comment by blakeembrey** [comment]
Emailed GitHub support as their directions say: https://github.com/github/markup/blob/master/CONTRIBUTING.md#contributing
